[CI] Improve dependency checker (#3777)
### 📝 Description
Using python script instead of bash command, just to make it easier to
support.

Script can be run in 2 modes:
1. check  - `check-dependencies`
2. fix - `bump-dependencies`

When running in the 1st mode, script shows the difference between the
latest and actual:

```
🔍 Latest docker-cli version: 28.3.3
📦 Makefile version:          28.3.3
✅ docker-cli version is up-to-date

🔍 Latest nginx version: 1.29
📦 Makefile version:          1.27
❌ nginx version is outdated or inconsistent
```

it is also possible, that, as in the case with nginx, we have multiple
images mentioned in the Makefile. They all will be checked and if there
is inconsistency in the Makefile itself, we will also be informed about
that:

```
✗ make check-dependencies  
🔍 Latest docker-cli version: 28.3.3
📦 Makefile version:          28.3.3
✅ docker-cli version is up-to-date

Error: Inconsistent versions for nginx in Makefile: 1.28, 1.29, 1.29
make: *** [check-dependencies] Error 1
```

When running in the 2nd mode, dependencies will be fixed automatically.
Example:

```
✅ docker-cli is already up-to-date: 28.3.3
🔄 Updating nginx:
   Old: NUCLIO_DOCKER_DASHBOARD_NGINX_BASE_IMAGE  ?= gcr.io/iguazio/arm32v7/nginx:1.27-alpine
   New: NUCLIO_DOCKER_DASHBOARD_NGINX_BASE_IMAGE  ?= gcr.io/iguazio/arm32v7/nginx:1.29-alpine
🔄 Updating nginx:
   Old: NUCLIO_DOCKER_DASHBOARD_NGINX_BASE_IMAGE  ?= gcr.io/iguazio/arm64v8/nginx:1.27-alpine
   New: NUCLIO_DOCKER_DASHBOARD_NGINX_BASE_IMAGE  ?= gcr.io/iguazio/arm64v8/nginx:1.29-alpine
🔄 Updating nginx:
   Old: NUCLIO_DOCKER_DASHBOARD_NGINX_BASE_IMAGE  ?= gcr.io/iguazio/nginx:1.27-alpine
   New: NUCLIO_DOCKER_DASHBOARD_NGINX_BASE_IMAGE  ?= gcr.io/iguazio/nginx:1.29-alpine
✅ Makefile updated to the latest versions.
```
---

---

### ✅ Checklist
- [ ] I updated the documentation (if applicable)
- [x] I have tested the changes in this PR
https://github.com/nuclio/nuclio/actions/runs/17154988838/job/48669634050?pr=3777

---

### 🧪 Testing
tested locally + by running once on the pr 

---

### 🔗 References
- Ticket link:https://iguazio.atlassian.net/browse/NUC-578
- Design docs links:
- External links:

---

### 🚨 Breaking Changes?

- [ ] Yes (explain below)
- [x] No