[Processor] Fix sync function streaming (#3850)
### 📝 Description
I. #3810 broke sync yield flow of streaming 

This PR:
1. fixes the breakage
2. ensures that these flows are covered by adding integration tests and
making sure that without the change, they fail
https://github.com/nuclio/nuclio/actions/runs/18725119036

```
--- FAIL: TestIntegrationSuite/python:3.11/TestStreamingHandler/sync_handler_as_sync_gen (15.96s)
```
II. This PR also includes a fix for long CI, because content type and
status code should be set before the body is set
---

### ✅ Checklist
- [ ] I updated the documentation (if applicable)
- [x] I have tested the changes in this PR

---

### 🧪 Testing
integration tests
---

### 🔗 References
- Ticket link: https://iguazio.atlassian.net/browse/NUC-631
- Design docs links:
- External links:

---

### 🚨 Breaking Changes?

- [ ] Yes (explain below)
- [x] No

<!-- If yes, describe what needs to be changed downstream: -->

---------

Co-authored-by: Noam Weiler <noamweiler1@gmail.com>